## conffiles
etc/argus/pepd/logging.xml
etc/argus/pepd/pepd.ini

## default (sysconfig)
etc/default/argus-pepd

## init.d
etc/init.d/argus-pepd

## others
usr/share/argus/pepd/sbin/pepdctl
var/lib/argus/pepd/lib/argus-pepd-1.6.1.jar
var/lib/argus/pepd/lib/commons-codec-1.3.jar
var/lib/argus/pepd/lib/commons-collections-3.1.jar
var/lib/argus/pepd/lib/commons-httpclient-3.0.1.jar
var/lib/argus/pepd/lib/commons-io-1.4.jar
var/lib/argus/pepd/lib/commons-lang-2.1.jar
var/lib/argus/pepd/lib/ehcache-core-1.7.2.jar
var/lib/argus/pepd/lib/ini4j-0.5.2.jar
var/lib/argus/pepd/lib/jcl-over-slf4j-1.5.8.jar
var/lib/argus/pepd/lib/jetty-6.1.18.jar
var/lib/argus/pepd/lib/jetty-java5-threadpool-6.1.18.jar
var/lib/argus/pepd/lib/jetty-sslengine-6.1.18.jar
var/lib/argus/pepd/lib/jetty-util-6.1.18.jar
var/lib/argus/pepd/lib/jna-3.0.9.jar
var/lib/argus/pepd/lib/jna-posix-1.0.3.jar
var/lib/argus/pepd/lib/joda-time-1.6.jar
var/lib/argus/pepd/lib/jul-to-slf4j-1.5.8.jar
var/lib/argus/pepd/lib/log4j-over-slf4j-1.5.8.jar
var/lib/argus/pepd/lib/logback-classic-0.9.18.jar
var/lib/argus/pepd/lib/logback-core-0.9.18.jar
var/lib/argus/pepd/lib/not-yet-commons-ssl-0.3.9.jar
var/lib/argus/pepd/lib/opensaml-2.3.2.jar
var/lib/argus/pepd/lib/openws-1.3.1.jar
var/lib/argus/pepd/lib/servlet-api-2.5-20081211.jar
var/lib/argus/pepd/lib/slf4j-api-1.5.8.jar
var/lib/argus/pepd/lib/velocity-1.5.jar
var/lib/argus/pepd/lib/xmlsec-1.4.3.jar
var/lib/argus/pepd/lib/xmltooling-1.2.2.jar
var/lib/argus/pepd/lib/endorsed/serializer-2.7.1.jar
var/lib/argus/pepd/lib/endorsed/xalan-2.7.1.jar
var/lib/argus/pepd/lib/endorsed/xercesImpl-2.9.1.jar
var/lib/argus/pepd/lib/endorsed/xml-apis-1.3.04.jar
var/lib/argus/pepd/lib/endorsed/xml-resolver-1.2.jar
var/lib/argus/pepd/lib/provided/bcmail-*.jar
var/lib/argus/pepd/lib/provided/bcprov-*.jar
var/lib/argus/pepd/lib/provided/canl-*.jar
var/lib/argus/pepd/lib/provided/voms-api-java-*.jar
